### PR TITLE
Add images to 0_download_data

### PR DESCRIPTION
**Pull request by jenna-tomkinson**
@gwaybio I have added the files into a NF1_Images folder. This is ready for review.

### CODE REVIEW

**Review by gwaybio — APPROVED** [review]
Looks good, a couple general comments:

1. Can you add a `README.md` file inside the `0_download_data` folder? This README should describe the dataset (and file name structure)
2. Does the preprocess module work with these specific relative paths? If not, it's worth updating (probably in a separate PR! (The README described above _does_ belong in this PR)
3. Please check your github configuration. I see two potential (minor) problem areas that would probably be good to address sooner than later:
    - Please make sure your local github config remotes are setup properly. This PR is trying to merge a branch from the `WayScience` upstream rather than merge a feature branch from the `jenna-tomkinson` fork.
    - In future pull requests, please make sure you are proposing to merge from a branch that contains the most recent commits. This PR does not include the history of the preprocessing module.

Happy to chat more about these items! After you add a README, there is no reason for me to re-review - merge at will!

**Comment by jenna-tomkinson** [comment]
@gwaybio 
1. I know you said you don't have to review but can you confirm that the description of the data is fine? I am going to make a figure to describe the file metadata format like what CFReT did which is easy but I want to confirm the rest.
2. The relative paths in 1_preprocessing_data is not the same as this so I will make a PR to change those. I had the images within that folder so now that we have a module for it, no need for the raw images to be there!

I will have these corrections done by Friday!

**Comment by gwaybio** [comment]
Looks good. Can you add a couple more details? Ask yourself, "what do people need to know to understand what the data are". Details like:

- Assay: Modified Cell Painting (what do the channels represent? What cell structures are they targeting?)
- Cells: Schwann cells
- Samples: (you have the detail about genotype already!)
- Microscope: GE Deltavision Elite
- Magnification: 20X (I think)
- 8 vs. 16 bit?
- Anything else?
- How many images?
- etc...

**Comment by jenna-tomkinson** [comment]
@gwaybio Before I update the relative paths in the preprocessing module, I wanted to make sure this PR is completed first. It is ready for review!

**Review by gwaybio — APPROVED** [review]
🎉

**Pull request merged**
